name: Build RPM
on:
  workflow_call:
    inputs:
      build-dir:
        required: true
        type: string
      build-package:
        required: true
        type: string

jobs:
  build-rpm:
    name: build-rpm
    container: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - name: Install tooling for source RPM build
        run: |
          dnf -y install rpkg @rpm-development-tools 'dnf-command(builddep)'

      - name: Check out sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download RPM Spec sources
        run: |
          cd ${{ inputs.build-dir }}
          spectool -g ./${{ inputs.build-package }}.spec

      - name: Install build dependencies
        run: |
          cd ${{ inputs.build-dir }}
          dnf -y builddep ./${{ inputs.build-package }}.spec

      - name: Build RPM
        run: |
          cd ${{ inputs.build-dir }}
          mkdir -p out
          rpkg local --out `pwd`/out

      - name: Install RPMs
        run: |
          cd ${{ inputs.build-dir }}
          dnf -y install ./out/*/*.rpm
          rpm -q -l autotiling
