name: rofi-wayland

on:
  push:
    paths:
      - rofi-wayland/**
    branches: [main]
  pull_request:
    paths:
      - rofi-wayland/**
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-upload.yml
    with:
      build-dir: ${{github.workflow}}
      build-package: ${{github.workflow}}
    secrets:
      COPR_CLI_CONFIG: ${{secrets.COPR_CLI_CONFIG}}
