name: Upload to COPR
on:
  workflow_call:
    inputs:
      build-dir:
        required: true
        type: string
      build-package:
        required: true
        type: string
    secrets:
      COPR_CLI_CONFIG:
        description: "COPR config"
        required: true

jobs:
  copr:
    name: copr
    container: fedora:latest
    runs-on: ubuntu-latest
    steps:
      - name: Install API token for copr-cli
        env:
          # The whole 6 line COPR config
          # To generate a new token: https://copr.fedorainfracloud.org/api/.
          COPR_CLI_CONFIG: ${{secrets.COPR_CLI_CONFIG}}
        run: |
          mkdir -p "$HOME/.config"
          echo "$COPR_CLI_CONFIG" >> "$HOME/.config/copr"
          cat ~/.config/copr

      - name: Install dependencies
        run: |
          dnf -y install copr-cli rpkg @rpm-development-tools

      - name: Check out sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download RPM Spec sources
        run: |
          cd ${{ inputs.build-dir }}
          spectool -g ./${{ inputs.build-package }}.spec

      - name: Submit the build to copr
        run: |
          cd ${{ inputs.build-dir }}
          rpkg copr-build -w "erikreider/packages"
